/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testergui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ayesh
 */
public class AddStaff extends javax.swing.JFrame {
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    String query=null;
    int[] arr={5,6,7};
    public AddStaff() {
        initComponents();
        try{Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String connectionURL="jdbc:sqlserver://localhost:1433;databaseName=BankingSystem;user=admin;password=admin";
            con=DriverManager.getConnection(connectionURL);
            
            this.setVisible(true);
            this.setLocationRelativeTo(null);
            //this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }
    public void addStaff(){
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionURL="jdbc:sqlserver://localhost:1433;databaseName=BankingSystem;user=admin;password=admin";
            con=DriverManager.getConnection(connectionURL);
            query="insert into Staff(FName,LName,NIC,DOB,Address,phoneNo,Email,Password,BrID,RaID)values(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst= con.prepareStatement(query);
            pst.setString(1,fnameTxt.getText());
            pst.setString(2, lnameTxt.getText());
            pst.setInt(3,Integer.parseInt(nicTxt.getText()));
            pst.setString(4,dobTxt.getText());
            pst.setString(5, addressTxt.getText());
            pst.setInt(6,Integer.parseInt(phonenoTxt.getText()));
            pst.setString(7,emailTxt.getText());
            pst.setString(8, passwordTxt.getText());
            pst.setInt(9,AdminData.brid);
            int rank=arr[rankidCBox.getSelectedIndex()];
            pst.setInt(10,rank);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Registered Sucessfrly!");
            this.dispose();
            
            
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        phonenoTxt = new javax.swing.JTextField();
        fnameTxt = new javax.swing.JTextField();
        dobTxt = new javax.swing.JTextField();
        nicTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        lnameTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        rankidCBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("New Staff");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("*Last Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 156, 100, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("*First Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 119, 100, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone No:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 119, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CNIC:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 156, 75, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DOB:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 198, 75, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 233, 90, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("*Password:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 198, 100, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 277, 90, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Rank ID:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 233, 80, -1));

        phonenoTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPanel1.add(phonenoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 116, 139, -1));

        fnameTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPanel1.add(fnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 116, 139, -1));

        dobTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPanel1.add(dobTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 195, 139, -1));

        nicTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPanel1.add(nicTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 153, 139, -1));

        passwordTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPanel1.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 139, -1));

        emailTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPanel1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 230, 139, -1));

        lnameTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPanel1.add(lnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 153, 139, -1));

        addressTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPanel1.add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 279, 440, -1));

        registerBtn.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        rankidCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", "7" }));
        jPanel1.add(rankidCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 130, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("E:\\4th samester\\DataBase\\Project data\\Interface\\Admin\\addstaff2.jpg")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        System.out.println(arr[rankidCBox.getSelectedIndex()]);
        if(fnameTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter First Name!");
        }
        else if(lnameTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Last Name!");
        }
        else if(passwordTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Password!");
        }
        else if(nicTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter CNIC!");
        }
        else{
            this.addStaff();
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JTextField nicTxt;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JTextField phonenoTxt;
    private javax.swing.JComboBox<String> rankidCBox;
    private javax.swing.JButton registerBtn;
    // End of variables declaration//GEN-END:variables
}
