/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testergui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ayesh
 */
public class AnswerQuries extends javax.swing.JFrame {
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    String query=null;
    int id;
    public AnswerQuries() {
        initComponents();
        savereplyBtn.setEnabled(false);
        try{Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String connectionURL="jdbc:sqlserver://localhost:1433;databaseName=BankingSystem;user=admin;password=admin";
            con=DriverManager.getConnection(connectionURL);
            
            this.setVisible(true);
            this.setLocationRelativeTo(null);
            //this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }
    public void getQuerie(){
        try{
             st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
             query="SELECT * FROM Queries where QrID='" + id + "' and AdID='"+AdminData.adid+"'";
             rs = st.executeQuery(query);
                boolean empty = true;
                if (rs.next()){
                    empty = false;
                    if(id==0){
                        JOptionPane.showMessageDialog(null,"Enter id!");
                    }
                    else{
                        
                        questionTxt.setText(rs.getString("Question"));
                        QueriesData data;
                        data= new QueriesData(rs.getInt("QrID"),rs.getString("QrDate"),rs.getString("Question"),rs.getString("Answer"));
                        savereplyBtn.setEnabled(true);
                    }
                }
                else 
                    JOptionPane.showMessageDialog(null,"invalid Querie ID!");
        }
        catch(Exception e)
        {
            System.out.println("error with connection "+e);
        }
    }
    public void saveAnswer(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionURL="jdbc:sqlserver://localhost:1433;databaseName=BankingSystem;user=admin;password=admin";
            con=DriverManager.getConnection(connectionURL);
            query="Update Queries set Answer=? where QrID='"+ id +"'";
            PreparedStatement pst= con.prepareStatement(query);
            pst.setString(1,answerTxt.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Saved Successfrly!");
            this.dispose();
            //System.out.println("Amount Update"+(amount+balance));
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        querieidTxt = new javax.swing.JTextField();
        getBtn = new javax.swing.JButton();
        questionTxt = new javax.swing.JLabel();
        answerTxt = new javax.swing.JTextField();
        savereplyBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quries");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Qurie ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 77, -1, -1));

        querieidTxt.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        getContentPane().add(querieidTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 74, 95, -1));

        getBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getBtn.setText("Get");
        getBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBtnActionPerformed(evt);
            }
        });
        getContentPane().add(getBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 75, -1, -1));

        questionTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        questionTxt.setForeground(new java.awt.Color(255, 255, 255));
        questionTxt.setText("Question:");
        getContentPane().add(questionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 118, 420, -1));

        answerTxt.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        getContentPane().add(answerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 159, 420, 109));

        savereplyBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        savereplyBtn.setText("Save Reply");
        savereplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savereplyBtnActionPerformed(evt);
            }
        });
        getContentPane().add(savereplyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 286, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\4th samester\\DataBase\\Project data\\Interface\\Admin\\addstaff2.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBtnActionPerformed
        // TODO add your handling code here:
        if(querieidTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Customer ID!");
        }
        id=Integer.parseInt(querieidTxt.getText());
        this.getQuerie();
    }//GEN-LAST:event_getBtnActionPerformed

    private void savereplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savereplyBtnActionPerformed
        // TODO add your handling code here:
        if(answerTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Write your answer first then press save button!");
        }
        this.saveAnswer();
    }//GEN-LAST:event_savereplyBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnswerQuries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnswerQuries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnswerQuries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnswerQuries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnswerQuries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerTxt;
    private javax.swing.JButton getBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField querieidTxt;
    private javax.swing.JLabel questionTxt;
    private javax.swing.JButton savereplyBtn;
    // End of variables declaration//GEN-END:variables
}
