/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testergui;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ayesh
 */
public class Deposit extends javax.swing.JFrame {
    
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    String query=null;
    int accountNo=-1;
    int amount=-1;
    int balance;

    /**
     * Creates new form Deposit
     */
    public Deposit() {
        initComponents();
        try{Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String connectionURL="jdbc:sqlserver://localhost:1433;databaseName=BankingSystem;user=admin;password=admin";
            con=DriverManager.getConnection(connectionURL);
            
            this.setVisible(true);
            this.setLocationRelativeTo(null);
            //this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountNoLabel = new javax.swing.JLabel();
        accountNoTxtField = new javax.swing.JTextField();
        accountNoLabel1 = new javax.swing.JLabel();
        amountFeild = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        depositButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accountNoLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        accountNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountNoLabel.setText("Enter Account No");
        getContentPane().add(accountNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        accountNoTxtField.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        accountNoTxtField.setToolTipText("AccountNo");
        accountNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNoTxtFieldActionPerformed(evt);
            }
        });
        getContentPane().add(accountNoTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 157, -1));

        accountNoLabel1.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        accountNoLabel1.setForeground(new java.awt.Color(255, 255, 255));
        accountNoLabel1.setText("Enter Amount");
        getContentPane().add(accountNoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        amountFeild.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        amountFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFeildActionPerformed(evt);
            }
        });
        getContentPane().add(amountFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 157, -1));

        jButton2.setText("Cancel");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });
        getContentPane().add(depositButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Deposit");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\4th samester\\DataBase\\Project data\\Interface\\Admin\\addstaff2.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNoTxtFieldActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
        try{
            accountNo=Integer.parseInt(accountNoTxtField.getText());
            amount=Integer.parseInt(amountFeild.getText());
        }
        catch(NumberFormatException numberFormateException){
            System.out.println(numberFormateException);
        }
        try{
            if(amount==-1||accountNo==-1){
                JOptionPane.showMessageDialog(null,"Please check the feilds");
            }
            else{
                try{
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionURL="jdbc:sqlserver://localhost:1433;databaseName=BankingSystem;user=admin;password=admin";
            con=DriverManager.getConnection(connectionURL);
            query="Select * from Account where CuID='"+accountNo+"'";
            st=con.createStatement();
            rs = st.executeQuery(query);
                    if(rs.next()){
                        balance=rs.getInt("Balance");
                        deposit();
                    }
                }
                catch(Exception e){
                    System.out.println(e);
                }
            }
            
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_depositButtonActionPerformed

    private void amountFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFeildActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNoLabel;
    private javax.swing.JLabel accountNoLabel1;
    private javax.swing.JTextField accountNoTxtField;
    private javax.swing.JTextField amountFeild;
    private javax.swing.JButton depositButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void deposit() {
        try {
            int temp=balance+amount;
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            query="UPDATE Account SET Balance="+temp+" WHERE AccID="+accountNo+"";
            PreparedStatement pst= con.prepareStatement(query);         
            pst.executeUpdate();
            depositRecord();
            JOptionPane.showMessageDialog(null, "Transection Succeful");
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(WithdrawForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void depositRecord() {
        try{
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionURL="jdbc:sqlserver://localhost:1433;databaseName=BankingSystem;user=admin;password=admin";
            con=DriverManager.getConnection(connectionURL);
            query="INSERT INTO deposit(Amount,DoDate,BrID,AccID,StID) VALUES (?,?,?,?,?)";
            PreparedStatement pst= con.prepareStatement(query);
            pst.setString(1,Integer.toString(amount));
            long millis=System.currentTimeMillis();  
            java.sql.Date date=new java.sql.Date(millis); 
            pst.setDate(2, date);
            pst.setInt(3,Staff.brid);
            pst.setInt(4,accountNo );
            pst.setInt(5,Staff.stid);
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(WithdrawForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(WithdrawForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
